"""Selects 20 diverse official DocILE train-split documents from the
existing qualified clean-candidate pool
(results/dataset_inspection/clean_candidate_scores.json,
all_qualifying_candidates_ranked -- 744 documents that already passed
the OCR-agreement and monetary-redundancy quality bar) for the Tell
probe-training activation corpus.

Selection is fully deterministic (seeded PRNG, docid-sorted inputs) so
it can be regenerated byte-for-byte. It enforces global vendor and
cluster_id uniqueness across all 20 selected documents (stronger than
the "no more than one split" requirement, and simpler to reason about),
then greedily maximizes feature diversity (currency, single/multi-page,
line-item-count bucket, amount bucket, OCR word-count bucket, invoice-
date format class, invoice-number format class) using a novelty-
maximizing greedy selection over a deterministically shuffled candidate
order. The 20 selected documents are then assigned to splits by cycling
a repeating [train, train, train, validation, test] pattern over
selection order, so diversity is spread across splits rather than
clumped into one.

Reads data/docile/annotations/<docid>.json directly only for
`metadata.page_count` (not present in clean_candidate_scores.json) --
every other feature used for diversity comes from the already-frozen
scores file. Touches no DocILE validation-split document (the scores
file itself is scanned only over `data/docile/annotations` train-split
document ids per the existing clean_candidate_scores.json generation
process).

Writes:
  - results/probe_dataset/document_selection_manifest.json
  - results/probe_dataset/document_selection_report.md
"""

from __future__ import annotations

import hashlib
import json
import random
import re
from decimal import Decimal, InvalidOperation
from pathlib import Path

CANDIDATE_SCORES_PATH = Path("/home/hp5/tell/results/dataset_inspection/clean_candidate_scores.json")
DOCILE_ANNOTATIONS_DIR = Path("/home/hp5/tell/data/docile/annotations")

OUTPUT_DIR = Path("/home/hp5/tell/results/probe_dataset")
MANIFEST_PATH = OUTPUT_DIR / "document_selection_manifest.json"
REPORT_PATH = OUTPUT_DIR / "document_selection_report.md"

N_TRAIN, N_VAL, N_TEST = 12, 4, 4
N_TOTAL = N_TRAIN + N_VAL + N_TEST

# Documents already used by prior, unrelated Tell experiments -- excluded
# so this corpus never accidentally reuses the same invoice as the
# hand-authored clean/attack scenarios (not a correctness requirement,
# just avoids confusing overlap in reports).
EXCLUDE_DOCIDS = {"04d531ca811f448a91c6ff4e", "002f9b82b74f4258b3b072d0"}

SEED = 20240923


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _parse_amount(text: str) -> float | None:
    cleaned = re.sub(r"[^0-9.\-]", "", text or "")
    if not cleaned:
        return None
    try:
        return float(Decimal(cleaned))
    except (InvalidOperation, ValueError):
        return None


def _amount_bucket(amount: float | None) -> str:
    if amount is None or amount <= 0:
        return "unknown"
    if amount < 100:
        return "under_100"
    if amount < 1_000:
        return "100_to_1k"
    if amount < 10_000:
        return "1k_to_10k"
    if amount < 100_000:
        return "10k_to_100k"
    return "over_100k"


def _word_count_bucket(n: int) -> str:
    if n < 60:
        return "short"
    if n < 150:
        return "medium"
    if n < 300:
        return "long"
    return "very_long"


def _line_item_bucket(n: int) -> str:
    if n <= 1:
        return "single"
    if n <= 3:
        return "few"
    return "many"


_DATE_MONTH_NAME_RE = re.compile(r"[A-Za-z]{3,}")


def _date_format_class(text: str | None) -> str:
    if not text:
        return "unknown"
    if _DATE_MONTH_NAME_RE.search(text):
        return "month_name"
    if "." in text:
        return "dot_separated"
    if "-" in text:
        return "dash_separated"
    if "/" in text:
        return "slash_separated"
    return "other"


def _invoice_number_format_class(text: str | None) -> str:
    if not text:
        return "unknown"
    if text.isdigit():
        return "numeric_only"
    if re.search(r"[A-Za-z]", text) and re.search(r"\d", text):
        return "alphanumeric"
    if "-" in text:
        return "hyphenated"
    return "other"


def _load_candidates() -> list[dict]:
    scores = json.loads(CANDIDATE_SCORES_PATH.read_text())
    return scores["all_qualifying_candidates_ranked"]


def _page_count(docid: str) -> int:
    ann = json.loads((DOCILE_ANNOTATIONS_DIR / f"{docid}.json").read_text())
    return int(ann["metadata"]["page_count"])


def _payable_amount_text(c: dict) -> tuple[str, str]:
    """The qualifying pool's own filter accepts `amount_total_gross` as
    the payable amount when `amount_due` is absent (see
    score_breakdown.monetary_redundancy_note on such candidates, e.g.
    "amount_due == amount_total_gross"). Returns (text, source_field)."""
    if c.get("amount_due"):
        return c["amount_due"], "amount_due"
    if c.get("amount_total_gross"):
        return c["amount_total_gross"], "amount_total_gross"
    return "", "none"


def _feature_signature(c: dict) -> dict:
    amount_text, _ = _payable_amount_text(c)
    amount = _parse_amount(amount_text)
    return {
        "currency": c.get("currency") or "unknown",
        "page_count_class": "multi_page" if c["page_count"] > 1 else "single_page",
        "line_item_bucket": _line_item_bucket(c.get("line_item_count", 0)),
        "amount_bucket": _amount_bucket(amount),
        "word_count_bucket": _word_count_bucket(c.get("ocr_word_count", 0)),
        "date_format_class": _date_format_class(c.get("invoice_date")),
        "invoice_number_format_class": _invoice_number_format_class(c.get("invoice_number")),
    }


def _vendor_key(vendor_name: str) -> str:
    return re.sub(r"\s+", " ", (vendor_name or "").strip().upper())


def main() -> None:
    raw_candidates = _load_candidates()
    print(f"[select] loaded {len(raw_candidates)} qualifying candidates")

    candidates = []
    n_excluded_zero_amount = 0
    for c in raw_candidates:
        if c["docid"] in EXCLUDE_DOCIDS:
            continue
        amount_text, _ = _payable_amount_text(c)
        amount_value = _parse_amount(amount_text)
        if amount_value is None or amount_value <= 0:
            # A zero or unparseable payable amount is not "unambiguous" in
            # the sense this corpus needs (a demo/probe email plausibly
            # referencing "the amount due" should not be $0.00) -- excluded
            # from the eligible pool rather than merely deprioritized.
            n_excluded_zero_amount += 1
            continue
        c = dict(c)
        c["page_count"] = _page_count(c["docid"])
        candidates.append(c)
    print(f"[select] {len(candidates)} candidates after excluding prior-experiment docids and {n_excluded_zero_amount} zero/unparseable-amount candidates")

    # Deterministic shuffle of candidate order (docid-sorted input, seeded
    # PRNG) -- greedy novelty selection then picks from this fixed order,
    # so results are exactly reproducible.
    candidates.sort(key=lambda c: c["docid"])
    rng = random.Random(SEED)
    order = list(range(len(candidates)))
    rng.shuffle(order)
    shuffled = [candidates[i] for i in order]

    selected: list[dict] = []
    used_vendor_keys: set[str] = set()
    used_cluster_ids: set[int] = set()
    seen_feature_values: dict[str, set[str]] = {}

    def _novelty_score(c: dict) -> int:
        sig = _feature_signature(c)
        score = 0
        for feature_name, value in sig.items():
            if value not in seen_feature_values.get(feature_name, set()):
                score += 1
        return score

    vendor_isolation_relaxed_for: list[str] = []
    cluster_isolation_relaxed_for: list[str] = []

    remaining = list(shuffled)
    while len(selected) < N_TOTAL and remaining:
        # Rank remaining candidates by (novelty desc, tiebreak_score desc, docid asc) --
        # fully deterministic ordering.
        remaining.sort(key=lambda c: (-_novelty_score(c), -c.get("tiebreak_score", 0.0), c["docid"]))
        pick = None
        for c in remaining:
            vendor_key = _vendor_key(c["vendor_name"])
            if vendor_key in used_vendor_keys or c["cluster_id"] in used_cluster_ids:
                continue
            pick = c
            break
        relaxed = False
        if pick is None:
            # Strict vendor+cluster isolation exhausted the pool before
            # reaching 20 documents -- relax cluster isolation first
            # (vendor identity is the more important diversity axis for
            # this corpus, since the synthetic vendor record is keyed off
            # docid+vendor, not cluster).
            for c in remaining:
                vendor_key = _vendor_key(c["vendor_name"])
                if vendor_key in used_vendor_keys:
                    continue
                pick = c
                relaxed = True
                break
        if pick is None:
            # Even vendor isolation is exhausted -- take the top-ranked
            # remaining candidate regardless (should not happen with a
            # 744-document pool and only 20 selections, but fail loudly
            # rather than silently looping forever if it does).
            pick = remaining[0]
            relaxed = True

        if relaxed:
            if _vendor_key(pick["vendor_name"]) in used_vendor_keys:
                vendor_isolation_relaxed_for.append(pick["docid"])
            if pick["cluster_id"] in used_cluster_ids:
                cluster_isolation_relaxed_for.append(pick["docid"])

        selected.append(pick)
        used_vendor_keys.add(_vendor_key(pick["vendor_name"]))
        used_cluster_ids.add(pick["cluster_id"])
        sig = _feature_signature(pick)
        for feature_name, value in sig.items():
            seen_feature_values.setdefault(feature_name, set()).add(value)
        remaining.remove(pick)

    if len(selected) != N_TOTAL:
        raise RuntimeError(f"Could not select {N_TOTAL} documents (got {len(selected)})")

    # ---- Split assignment: cycle [train, train, train, validation, test]
    # over selection order (which already alternates diverse features due
    # to greedy novelty selection), so diversity spreads across splits. ----
    split_pattern = ["train", "train", "train", "validation", "test"]
    splits: dict[str, list[dict]] = {"train": [], "validation": [], "test": []}
    for i, c in enumerate(selected):
        split = split_pattern[i % len(split_pattern)]
        splits[split].append(c)

    assert len(splits["train"]) == N_TRAIN
    assert len(splits["validation"]) == N_VAL
    assert len(splits["test"]) == N_TEST

    all_docids = [c["docid"] for c in selected]
    assert len(all_docids) == len(set(all_docids)), "duplicate docid selected"

    documents = []
    for split_name, docs in splits.items():
        for c in docs:
            sig = _feature_signature(c)
            payable_amount_text, payable_amount_source = _payable_amount_text(c)
            if not payable_amount_text:
                raise RuntimeError(f"{c['docid']} has no usable payable amount (amount_due and amount_total_gross both empty)")
            documents.append(
                {
                    "docid": c["docid"],
                    "split": split_name,
                    "vendor_name": c["vendor_name"],
                    "cluster_id": c["cluster_id"],
                    "document_type": c["document_type"],
                    "currency": c["currency"],
                    "invoice_number": c["invoice_number"],
                    "invoice_date": c["invoice_date"],
                    "amount_due": c["amount_due"],
                    "payable_amount_text": payable_amount_text,
                    "payable_amount_source": payable_amount_source,
                    "line_item_count": c["line_item_count"],
                    "ocr_word_count": c["ocr_word_count"],
                    "page_count": c["page_count"],
                    "tiebreak_score": c.get("tiebreak_score"),
                    "annotation_sha256": _sha256_file(DOCILE_ANNOTATIONS_DIR / f"{c['docid']}.json"),
                    "annotation_path": str(DOCILE_ANNOTATIONS_DIR / f"{c['docid']}.json"),
                    "diversity_signature": sig,
                }
            )

    diversity_coverage = {}
    for feature_name in ("currency", "page_count_class", "line_item_bucket", "amount_bucket", "word_count_bucket", "date_format_class", "invoice_number_format_class"):
        values = sorted({d["diversity_signature"][feature_name] for d in documents})
        diversity_coverage[feature_name] = values

    documented_limitations = []
    if diversity_coverage["page_count_class"] == ["single_page"]:
        documented_limitations.append(
            "Single- vs. multi-page diversity could not be achieved: every one of the 744 qualifying "
            "clean-candidate-pool documents (verified by scanning metadata.page_count for the entire pool, "
            "not just the 20 selected) is single-page. This is a property of the underlying qualified pool, "
            "not a selection defect -- no multi-page document exists to select."
        )
    n_fallback_amount = sum(1 for d in documents if d["payable_amount_source"] == "amount_total_gross")
    if n_fallback_amount:
        documented_limitations.append(
            f"{n_fallback_amount} selected document(s) have a null `amount_due` field and use `amount_total_gross` "
            "as the payable amount instead -- the same fallback the clean-candidate pool's own qualification "
            "filter already accepted for these documents (see score_breakdown.monetary_redundancy_note)."
        )

    manifest = {
        "seed": SEED,
        "candidate_scores_path": str(CANDIDATE_SCORES_PATH),
        "candidate_scores_sha256": _sha256_file(CANDIDATE_SCORES_PATH),
        "n_candidates_scanned": len(raw_candidates),
        "n_candidates_after_exclusions": len(candidates),
        "n_excluded_zero_or_unparseable_amount": n_excluded_zero_amount,
        "excluded_docids": sorted(EXCLUDE_DOCIDS),
        "n_train": N_TRAIN,
        "n_validation": N_VAL,
        "n_test": N_TEST,
        "documents": documents,
        "vendor_isolation": "global (no vendor reused across any of the 20 selected documents)" if not vendor_isolation_relaxed_for else f"relaxed for: {vendor_isolation_relaxed_for}",
        "cluster_isolation": "global (no cluster_id reused across any of the 20 selected documents)" if not cluster_isolation_relaxed_for else f"relaxed for: {cluster_isolation_relaxed_for}",
        "vendor_isolation_relaxed_for": vendor_isolation_relaxed_for,
        "cluster_isolation_relaxed_for": cluster_isolation_relaxed_for,
        "diversity_coverage": diversity_coverage,
        "documented_limitations": documented_limitations,
        "split_assignment_method": "cycled [train, train, train, validation, test] over the greedy-novelty selection order",
        "selection_method": (
            "Deterministic seeded shuffle of the 744-candidate pool, then greedy novelty-maximizing selection: "
            "at each step, among documents not yet violating global vendor/cluster uniqueness, pick the one "
            "contributing the most previously-unseen diversity-feature values (currency, single/multi-page, "
            "line-item-count bucket, amount bucket, OCR word-count bucket, invoice-date format class, "
            "invoice-number format class), tie-broken by the existing clean-candidate quality tiebreak_score, "
            "then by docid for full determinism."
        ),
    }
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2))

    lines = ["# Probe Corpus: Document Selection Report\n"]
    lines.append(
        f"Selected {N_TOTAL} documents from {len(candidates)} eligible qualifying candidates "
        f"(of {len(raw_candidates)} scanned, {len(EXCLUDE_DOCIDS)} excluded as already used by prior experiments).\n"
    )
    lines.append(f"Vendor isolation: **{manifest['vendor_isolation']}**\n")
    lines.append(f"Cluster isolation: **{manifest['cluster_isolation']}**\n")
    lines.append("## Diversity coverage across the 20 selected documents\n")
    for feature_name, values in diversity_coverage.items():
        lines.append(f"- `{feature_name}`: {', '.join(values)}")
    lines.append("")
    if documented_limitations:
        lines.append("## Documented limitations (relaxations from the ideal diversity target)\n")
        for note in documented_limitations:
            lines.append(f"- {note}")
        lines.append("")
    for split_name in ("train", "validation", "test"):
        docs = [d for d in documents if d["split"] == split_name]
        lines.append(f"## {split_name} ({len(docs)} documents)\n")
        lines.append("| docid | vendor | cluster | currency | amount_due | line_items | words | pages | date fmt | invnum fmt |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|")
        for d in docs:
            sig = d["diversity_signature"]
            lines.append(
                f"| `{d['docid']}` | {d['vendor_name']} | {d['cluster_id']} | {d['currency']} | {d['amount_due']} | "
                f"{d['line_item_count']} | {d['ocr_word_count']} | {d['page_count']} | {sig['date_format_class']} | {sig['invoice_number_format_class']} |"
            )
        lines.append("")

    lines.append("## Notes\n")
    lines.append(
        "All 20 documents are drawn from `results/dataset_inspection/clean_candidate_scores.json`'s "
        "`all_qualifying_candidates_ranked` list, which already passed the OCR-agreement and monetary-redundancy "
        "quality filters (hard filters 1-9 plus the OCR-agreement filter) over the official DocILE **train** "
        "split -- no DocILE validation document is scanned or selected here.\n"
    )
    REPORT_PATH.write_text("\n".join(lines))

    print(f"Wrote {MANIFEST_PATH}")
    print(f"Wrote {REPORT_PATH}")
    print(f"Vendor isolation relaxed for: {vendor_isolation_relaxed_for}")
    print(f"Cluster isolation relaxed for: {cluster_isolation_relaxed_for}")


if __name__ == "__main__":
    main()
