"""Regenerate tell-signals-data.js for the tell-signals-* mockups.

    python3 demo/ui-mockups/build_signals_data.py

Embeds the replay bundle (validated with trace_contract, so the audit chain, zones and
provenance are checked here, not re-derived in the browser) plus the measured/calculated
facts the mockups quote. Every fact carries its evidence kind and source path.
"""
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "ui"))
import trace_contract as tc  # noqa: E402

bundle = json.loads((HERE.parent / "ui_ocr/data/traces_v1.json").read_text())
tc.validate_bundle(bundle)  # raises on a broken hash chain / zone mismatch / missing provenance

check = {
    "validator": "trace_contract.validate_bundle",
    "valid": True,
    "traces": len(bundle["traces"]),
    "events": sum(len(t["events"]) for t in bundle["traces"]),
}

# Numbers from TELL_CONTEXT_FOR_FRONTEND.md §5; update here when the three-arm eval lands.
P = "results/probe_training/enterprise_v1/final_report.md"
R = "results/routing_design/tell_typed_verifier_v1.md"
E = "results/economics/enterprise_v1_1/"
facts = {
    "device": {"name": "HP ZGX Nano", "chip": "NVIDIA GB10", "unified_gib": 121.6, "kind": "measured"},
    "model": {"id": "Qwen/Qwen3-8B", "dtype": "BF16", "params_b": 8.19, "kind": "measured"},
    "runtime": [
        {"label": "Peak memory", "value": "16.4–17.9 GB", "kind": "measured"},
        {"label": "Tell capture (one turn)", "value": "0.78 s", "kind": "measured"},
        {"label": "Warm 4-turn workflow", "value": "31.5 s", "kind": "measured"},
        {"label": "Cold model load (one-time)", "value": "≈103 s", "kind": "measured"},
        {"label": "Tokens per workflow", "value": "12,473", "kind": "measured"},
        {"label": "Full pipeline end-to-end", "value": "not yet measured", "kind": "gap"},
    ],
    "auroc": [
        {"label": "Held-out test", "value": 0.841, "recall": 0.95, "fpr": 0.72},
        {"label": "Lexical paraphrase", "value": 0.717, "recall": 0.96, "fpr": 0.85},
        {"label": "Delayed memory (OOD)", "value": 0.609, "recall": 0.727, "fpr": 0.62},
    ],
    "auroc_source": P,
    "three_zone": [
        {"partition": "Held-out (400)", "agent_1": 16.5, "verify": 39.0, "agent_s": 44.5, "recall": 0.805, "false_alarm": 0.365},
        {"partition": "Lexical (400)", "agent_1": 9.5, "verify": 40.75, "agent_s": 49.75, "recall": 0.725, "false_alarm": 0.495},
        {"partition": "Delayed memory (600)", "agent_1": 32.7, "verify": 37.0, "agent_s": 30.3, "recall": 0.727, "false_alarm": 0.587},
    ],
    "three_zone_source": R,
    "economics": {
        "hardware_usd": 6500, "hardware_kind": "quote",
        "opex_usd_month": 10, "opex_kind": "assumption",
        "tokens_in": 12207, "tokens_out": 266, "tokens_kind": "measured",
        "capacity_month": 83000, "capacity_kind": "calculated",
        "tiers": {"low": [0.15, 0.60], "mid": [1, 4], "premium": [3, 15]}, "tiers_kind": "assumption",
        "source": E,
    },
    "pilots": {"unauthorized_payments": 0, "note": "All recorded attack pilots, one invoice, n=1–5 each", "kind": "measured"},
}

out = HERE / "tell-signals-data.js"
out.write_text(
    "/* GENERATED by build_signals_data.py — do not edit. */\n"
    f"window.TELL_BUNDLE={json.dumps(bundle, ensure_ascii=False)};\n"
    f"window.TELL_CHECK={json.dumps(check)};\n"
    f"window.TELL_FACTS={json.dumps(facts, ensure_ascii=False)};\n"
)
print(f"wrote {out.name}: {check['traces']} traces, {check['events']} events, bundle valid")
